[project]
name = "fake-openai"
version = "0.1.0"
description = "Useful for debugging issues with OpenAI calls"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "uvicorn>=0.34.2",
]
